# Generated by Django 5.0.9 on 2025-04-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('pai', models.IntegerField(blank=True, null=True)),
                ('inativa', models.IntegerField(default=0)),
                ('posicao', models.IntegerField(blank=True, max_length=30, null=True)),
                ('natureza', models.CharField(blank=True, choices=[('DESPESA', 'DESPESA'), ('RECEITA', 'RECEITA')], max_length=30, null=True)),
                ('tipo', models.BooleanField(blank=True, default=False, null=True)),
                ('hieraquia', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('balancete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.balancete')),
            ],
        ),
    ]
