# Generated by Django 5.0.9 on 2025-04-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ANALITICA', 'ANALITICA'), ('SINTETICA', 'SINTETICA')], max_length=30, null=True),
        ),
    ]
