# Generated by Django 5.0.9 on 2025-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_conta_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='hieraquia',
            new_name='hierarquia',
        ),
    ]
