# Generated by Django 5.0.9 on 2025-04-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_rename_hieraquia_conta_hierarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='cd_varejo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='codigo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
