# Generated by Django 5.0.9 on 2025-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_conta_cd_varejo_alter_conta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='posicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
