# Generated by Django 5.0.9 on 2025-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_alter_conta_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancete',
            name='calculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
