# Generated by Django 5.0.9 on 2026-03-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auditoria_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', help_text='URL de uma imagem de capa do painel. Se vazio, usa iframe de pré-visualização.', max_length=500),
        ),
    ]
